server:
  port: 8762   #端口号

eureka:
  instance:
    hostname: localhost  #localhost
    appname: eurekaserver
  client:
    #当前Eureka服务是单机版的
    # 是否注册到eureka
    #register-with-eureka: false
    # 是否从eureka获取注册信息
    #fetch-registry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8761/eureka/

